### ISSUE TITLE
The list breaks tradingview.com

### ISSUE THREAD

**Issue by schlaubstar** [mtxadmin/ublock#10]
The list contains a lot of domains and subdomains of tradingview.com - and thus completely breaks the functionality. Tradingview is stock-charting provider that I never encountered to be part of ads etc. The also blocked subdomains are necessary e.g. for functionality like alerts on certain events etc - I would consider to remove tradingview from the filterlist.

**Comment by mtxadmin** [comment]
Test it now, please.
