### ISSUE TITLE
additional selector for filter

### ISSUE THREAD

**Issue by webtask-pro** [mtxadmin/ublock#11]
Hi. I have some troubles with yandex.direct banners.  I can't block by css selector $= or ^=
$= this is mean last part of string
   class="zOkeOlan76rw41Ayf__loyier-exsist"   
##div[class$="__loyier-exsist"] - must blocked this element
same for "~=" part string in middle string
and "^=" start form

Can you add this support in future version?

**Comment by mtxadmin** [comment]
Sorry, I didn't see the issue because you had closed it.

Recently, I tried to block yandex.direct banners by "brute-force" listing their random classes. But it is not very good way to do it. Better way is to block yandex.direct through Javascript, as authors of Ru Adlist do.
