### ISSUE TITLE
 vscode-update.trafficmanager.net is blocked

### ISSUE THREAD

**Issue by aravindvnair99** [mtxadmin/ublock#12]
There seems no reason to block `vscode-update.trafficmanager.net`. Blocking it prevents VS Code updates on Pi-hole.

**Comment by mtxadmin** [comment]
Removed, please update.

**Comment by aravindvnair99** [comment]
Fixed in https://github.com/mtxadmin/ublock/commit/f31cddb2d36d01f5989d6842807ebaca7193b541
