### ISSUE TITLE
Can't click on share, save, and three dots button below video

### ISSUE THREAD

**Issue by alex4rks** [mtxadmin/ublock#13]
![image](https://user-images.githubusercontent.com/21969393/88376562-586c9e00-cda6-11ea-9232-cce70e1e5962.png)

**Comment by alex4rks** [comment]
tested on freshly installed firefox ublock addon with default filters

**Comment by mtxadmin** [comment]
Youtube share button disabled intentionally. This rule exists also in other lists like AdGuard, Fanboy's. You can make an exclusion:
youtube.com#@#.ytp-share-button

At three dots button I will see later.

**Comment by mtxadmin** [comment]
It turns out it was my mistake. Please update the list and try again.

**Comment by alex4rks** [comment]
now all 3 buttons are working, even without youtube.com#@#.ytp-share-button and
