### ISSUE TITLE
hosts.txt breaks microchip.com official domains

### ISSUE THREAD

**Issue by ysdemiranda** [mtxadmin/ublock#16]
Match found in https://raw.githubusercontent.com/mtxadmin/ublock/master/hosts.txt:
   cnwww.microchip.comv2.edgekey.net
Renders visits to official microchip.com impossible in pi-hole.
Fixed by adding a whitelist entry.
`\.microchip\.com$`

**Comment by mtxadmin** [comment]
edgekey.net is marketing domain, and exists in some lists. For instance, in MobileAdTrackers. I rechecked it now and still find this domain highly suspicious. By the way, microchip.com renders fine on my test browsers.

**Comment by mtxadmin** [comment]
... but after short googling it came out I was wrong. This domain belongs to Akamai CDN. Good, thanks to helping clear this out.

I fast removed all the occurences of edgekey.net subdomains from hosts.txt (even analytics etc for now). Please update.

**Comment by mtxadmin** [comment]
Plus (minus) edgesuite.net which also exists in some lists.

**Comment by ysdemiranda** [comment]
Updated and verified removal of said domains, also verified microchip.com and related domains can now be successfully reached without the whitelist regex. Thanks!
