### ISSUE TITLE
panorama.pub and www.panorama.pub

### ISSUE THREAD

**Issue by p-hash** [mtxadmin/ublock#18]
Humour is not an advertisement ^_^

**Comment by mtxadmin** [comment]
It seems, you are using hosts file? Yes, its version it is pretty old :-(

In late 2020 I removed panorama.pub from fakenews sublists. You are right, their articles are cool and sometimes indistinguishable from reality.

**Comment by p-hash** [comment]
Yep, I am using hosts files coz pihole (DNS ad-blocker) can process them. Can you update them? It'd be gladly appreciated

**Comment by mtxadmin** [comment]
Made a quick edit. Still hope to refactor building scripts, which still in todo, sorry :-)

By the way, does pi-hole have some special format for hostnames, which may be more optimized or compact? Or hosts file is pretty good for it?

**Comment by p-hash** [comment]
You can feed it a list of domains separated by newline, like [this one](https://raw.githubusercontent.com/deathbybandaid/piholeparser/master/Subscribable-Lists/CountryCodesLists/Russia.txt). Works fine for me.

**Comment by mtxadmin** [comment]
Maybe pi-hole supports asterisks? Like
```admob.*```
Instead of
```
admob.biz
admob.co.nz
admob.co.uk
admob.com
admob.de
admob.dk
admob.es
admob.fi
admob.fr
admob.gr
admob.it
admob.jp
admob.kr
admob.mobi
admob.net
admob.no
admob.pt
admob.ru
admob.sg
admob.tw
admob.google.com
```

or
`*.doubleclick.net`

instead of
```
ae.doubleclick.net
ar.doubleclick.net
at.doubleclick.net
au.doubleclick.net
be.doubleclick.net
br.doubleclick.net
ca.doubleclick.net
ch.doubleclick.net
cl.doubleclick.net
cn.doubleclick.net
co.doubleclick.net
cz.doubleclick.net
de.doubleclick.net
dk.doubleclick.net
es.doubleclick.net
fi.doubleclick.net
fls.doubleclick.net
fr.doubleclick.net
g.doubleclick.net
gr.doubleclick.net
gt.doubleclick.net
hk.doubleclick.net
hr.doubleclick.net
hu.doubleclick.net
ie.doubleclick.net
il.doubleclick.net
intl.doubleclick.net
is.doubleclick.net
it.doubleclick.net
jp.doubleclick.net
kr.doubleclick.net
kw.doubleclick.net
l.doubleclick.net
partnerad.l.doubleclick.net
ma.doubleclick.net
mo.doubleclick.net
mx.doubleclick.net
my.doubleclick.net
n2434.doubleclick.net
n3285ad.doubleclick.net
n3349ad.doubleclick.net
nat.doubleclick.net
den01.nat.doubleclick.net
den02.nat.doubleclick.net
den03.nat.doubleclick.net
nl.doubleclick.net
no.doubleclick.net
nz.doubleclick.net
ph.doubleclick.net
pl.doubleclick.net
pt.doubleclick.net
ro.doubleclick.net
rs.doubleclick.net
ru.doubleclick.net
sa.doubleclick.net
se.doubleclick.net
sg.doubleclick.net
si.doubleclick.net
sk.doubleclick.net
terra.doubleclick.net
th.doubleclick.net
tr.doubleclick.net
tw.doubleclick.net
uk.doubleclick.net
us.doubleclick.net
ve.doubleclick.net
video.doubleclick.net
za.doubleclick.net
```

Sorry for bothering you :-)

**Comment by p-hash** [comment]
Unfortunately, you cant do this. 

Longer explanation [here](https://discourse.pi-hole.net/t/using-blocklist-to-add-wildcard-blocked-domains/13561/10)
