### ISSUE TITLE
buymeacoffee.com shouldn't be blocked

### ISSUE THREAD

**Issue by aravindvnair99** [mtxadmin/ublock#19]
As the title suggests, I see no reason to block `buymeacoffee.com` which is just a platform for content creators, programmers, etc to be funded.

**Comment by mtxadmin** [comment]
Their asking widgets are annoying.

**Comment by aravindvnair99** [comment]
> Their asking widgets are annoying.

Ahh... @mtxadmin Isn't there a way to block just the annoying widgets, but unblock some necessary domains? I'm using the hosts file in Pi-Hole and when I search for `buymeacoffee.com`, I get:

   ```
blog.buymeacoffee.com 
   building.buymeacoffee.com 
   buymeacoffee.com 
   cdn.buymeacoffee.com 
   cdnjs.buymeacoffee.com 
   chat.buymeacoffee.com 
   chat-stage.buymeacoffee.com 
   community.buymeacoffee.com 
   creators.buymeacoffee.com 
   developers.buymeacoffee.com 
   e1.buymeacoffee.com 
   elastic.buymeacoffee.com 
   help.buymeacoffee.com 
   img.buymeacoffee.com 
   play.buymeacoffee.com 
   rd1.buymeacoffee.com 
   rose.buymeacoffee.com 
   search.buymeacoffee.com 
   stage.buymeacoffee.com 
   www.buymeacoffee.com
```

**Comment by mtxadmin** [comment]
I made a remove of all domains of buymeacoffee.com from hosts.txt. Please update.

**Comment by aravindvnair99** [comment]
> I made a remove of all domains of buymeacoffee.com from hosts.txt. Please update.

@mtxadmin, noted!

Closing this issue as it's been fixed with commits https://github.com/mtxadmin/ublock/commit/f8a4ec5363f3b29c7c19dbd5822987165f35a49e and https://github.com/mtxadmin/ublock/commit/709711d096dfe6feb9462a70a6d91bdf3641ccc5.
