### ISSUE TITLE
ads on ok.ru

### ISSUE THREAD

**Issue by baldadada** [mtxadmin/ublock#2]
Yet another small uBlock filter list creates ads on this site. (https://www.ok.ru)

https://www.myvi.tv/embed/9z938topw97r7r4cgftdgreabe

**Comment by mtxadmin** [comment]
Use https://youtube.com instead :-)

**Comment by baldadada** [comment]
> Используйте https://youtube.com вместо :-) 
youtube unavailable :(
[Запись_2019_08_25_09_41_23_642.zip](https://github.com/mtxadmin/ublock/files/3549135/_2019_08_25_09_41_23_642.zip)

**Comment by mtxadmin** [comment]
Жутко извиняюсь, не увидел приложенный файл с видео. Переоткрыл, надо будет посмотреть, что там может быть.

**Comment by mtxadmin** [comment]
Добрался, наконец, до Одноклассников - рекламы там, ожидаемо, не вижу.

Технически не понимаю, откуда и как это могло вылезти - исключений в этой подписке практически нет. Если то окно всё еще вылезает, давайте подробности, очень любопытный случай.

**Comment by baldadada** [comment]
> Добрался, наконец, до Одноклассников - рекламы там, ожидаемо, не вижу.
> 
> Практически нет. Если все еще вылезает, давайте подробности, очень любопытный случай.

Проверил. Ради чистоты эксперимента поставил ублок с нуля, и подписался только на ваш фильтр - рекламы нет (слава богу). Спасибо.

**Comment by mtxadmin** [comment]
Сожалею, что это заняло столько времени и вызвало недопонимание вначале :-)

**Comment by baldadada** [comment]
Да ничего, главное что рабтает)
