### ISSUE TITLE
statuspage.io

### ISSUE THREAD

**Issue by aravindvnair99** [mtxadmin/ublock#22]
`Statuspage` is just a status and incident communication tool by Atlassian. It should not be blocked as it doesn't fall under ads or malware or anything unwanted.

There are many more subdomains also present.

**Comment by mtxadmin** [comment]
It seems, it was false positive - I looked at their slogan "Easily communicate real-time status to your users" and decided it is some kind of chatbot or marketing tool :-)

Removed completely, thanks.
