### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by aravindvnair99** [mtxadmin/ublock#25]
Internationalized Domain Names (IDN) should be converted to ASCII-Compatible Encoding (ACE) form before entering it into the DNS server. The `hosts` file should only contain ASCII compatible domains.

```
Sample of invalid domains:
      - discörd.com
      - discördapp.com
      - disçordapp.com
      - minecräft.com
      - rëddït.com
```

Reference: [Internationalized Domain Name (IDN) Conversion Tool - VeriSign](https://www.verisign.com/en_US/channel-resources/domain-registry-products/idn/idn-conversion-tool/index.xhtml)

**Comment by mtxadmin** [comment]
Oh, thanks! These ones were making errors in my scripts :-)

Also, I found some more such non-ASCII domains and replaced them too, and removed duplicates.
