### ISSUE TITLE
embedly.com

### ISSUE THREAD

**Issue by aravindvnair99** [mtxadmin/ublock#26]
Blocks this prevents website which uses the CDN from loading. Such as an [article](https://betterprogramming.pub/understanding-css-display-none-block-inline-and-inline-block-63f6510df93) on Medium for example.

Blocked URLs:

```
   api.embedly.com 
   api-cdn.embedly.com 
   cdn.embedly.com 
   embedly.com 
   pro.embedly.com 
   staging.cdn.embedly.com 
   v.embedly.com 
   v-cdn.embedly.com 
   www.embedly.com 
```

**Comment by mtxadmin** [comment]
Hmm... I see nothing embedded from embedly.com there.

**Comment by mtxadmin** [comment]
It turns out, loading of such elements need scrolling. 

Iframes to https://cdn.embedly.com/widgets/media.html?src=https....

**Comment by aravindvnair99** [comment]
> It turns out, loading of such elements need scrolling.
> 
> Iframes to https://cdn.embedly.com/widgets/media.html?src=https....

@mtxadmin  It doesn't load:

![image](https://user-images.githubusercontent.com/22199259/110215591-9a2efc80-7ed0-11eb-8601-e66cf160d2eb.png)

**Comment by aravindvnair99** [comment]
> Hmm... I see nothing embedded from embedly.com there.

@mtxadmin Links from that article:

- [1st iframe](https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fcodepen.io%2Fcem_eygi%2Fembed%2Fpreview%2FrQWQpQ%3Fheight%3D600%26slug-hash%3DrQWQpQ%26default-tabs%3Dcss%2Cresult%26host%3Dhttps%3A%2F%2Fcodepen.io&url=https%3A%2F%2Fcodepen.io%2Fcem_eygi%2Fpen%2FrQWQpQ&image=https%3A%2F%2Fscreenshot.codepen.io%2F2315188.rQWQpQ.small.0978ad87-4c3e-430c-8c68-6c0b545c90b3.png&key=a19fcc184b9711e1b4764040d3dc5c07&type=text%2Fhtml&schema=codepen)
- [2nd iframe](https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FAA0jJeRCwG0%3Ffeature%3Doembed&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DAA0jJeRCwG0&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FAA0jJeRCwG0%2Fhqdefault.jpg&key=a19fcc184b9711e1b4764040d3dc5c07&type=text%2Fhtml&schema=youtube)
- [3rd iframe](https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FhgoFi0fCv3w%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DhgoFi0fCv3w&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FhgoFi0fCv3w%2Fhqdefault.jpg&key=a19fcc184b9711e1b4764040d3dc5c07&type=text%2Fhtml&schema=youtube)

**Comment by mtxadmin** [comment]
Yes, a false positive... I always look very suspiciously for third-party elements on pages, but this case is clearly ok. Thanks for pointing out for it.
