### ISSUE TITLE
vsmarketplacebadge.apphb.com

### ISSUE THREAD

**Issue by aravindvnair99** [mtxadmin/ublock#27]
Blocking apphb.com blocks badges in VS Code.

Connected to: [AppHarbor](https://appharbor.com)

AppHarbor is a fully hosted .NET Platform as a Service. AppHarbor can deploy and scale any standard .NET application to the cloud.

Reference: https://github.com/Microsoft/vscode/issues/46993

**Comment by mtxadmin** [comment]
I've seen strange scripts on some shopify shops. But, in general, you are right, apphb should not be blocked as whole platform.
