### ISSUE TITLE
wsimg.com

### ISSUE THREAD

**Issue by aravindvnair99** [mtxadmin/ublock#29]
Blocking this prevents GoDaddy from loading. It was trying to connect to `img6.wsimg.com`

![image](https://user-images.githubusercontent.com/22199259/110242102-76c08c00-7f7a-11eb-90ed-be9dfad5c89c.png)

Blocked domains are:

```
   blobby.wsimg.com 
   img1.wsimg.com 
   img2.wsimg.com 
   img3.wsimg.com 
   img4.wsimg.com 
   img5.wsimg.com 
   img6.wsimg.com 
   isteam.wsimg.com 
   nebula.wsimg.com 
   online.wsimg.com 
   onlinestore.wsimg.com 
   shops1.wsimg.com 
   tencent.wsimg.com 
   wsimg.com
```

**Comment by mtxadmin** [comment]
In my test browser, Godaddy loads ok, but blocked two (telemetry?) scripts:
https://img6.wsimg.com/wrhs/*/heartbeat.min.js
https://img6.wsimg.com/wrhs/*/tcc.min.js
As for me, that looks good

But domains shouldn't be blocked. Looks like, it was a script error. Removed and transfered them to different source sublist for sure.

According to your screenshot, there still may be issues with blocked scripts on Godaddy when using full list. Maybe these rules require narrowing down someday.

**Comment by mtxadmin** [comment]
Oh, yes. I have the same picture with blocked scripts as you - tried to make an account :-(

Some narrowing...

**Comment by aravindvnair99** [comment]
> Oh, yes. I have the same picture with blocked scripts as you - tried to make an account :-(
> 
> Some narrowing...

@mtxadmin Oh sorry, I forgot to mention what I was doing... I got the error when I was trying to use the domain search tool.

**Comment by mtxadmin** [comment]
After removing hosts from hostfile, is it ok now?

**Comment by aravindvnair99** [comment]
> After removing hosts from hostfile, is it ok now?

Hey @mtxadmin! I'm currently travelling and not at home. So I can't test it right now as I'm not with my Pi-Hole.

**Comment by mtxadmin** [comment]
Glad for you :-)

Hope you are vaccinated already. Last news about India are not very good.
