### ISSUE TITLE
Огромный hosts файл

### ISSUE THREAD

**Issue by dimqua** [mtxadmin/ublock#3]
В чем причина такой существенной разницы между фильтром для uBO и файлом hosts?

![](https://user-images.githubusercontent.com/540898/65785662-9afd2400-e15d-11e9-8437-60806b583638.png)

Наличие ста тысяч доменов в hosts увеличивает нагрузку на мобильные устройства. И повышает риск получить ложные срабатывания (false-positives).

Можно ли что-то с этим сделать? Вероятно, стоит разбить hosts на несколько файлов (по категориям), например, `hosts-ads`, `hosts-privacy`, `hosts-malware` и т.д.

**Comment by mtxadmin** [comment]
В файле hosts перечисляются субдомены. Это необходимо, поскольку hosts из наличия в нем какого-нибудь домена, для примера, adtech.de не сможет вывести адреса *.adtech.de, например, img-origin-us-west-1.prod.adtech.de . Отсюда и большой объем.

По поводу увеличения нагрузки на мобильные устройства - я не могу это подтвердить ни по своему опыту, ни по материалам в сети. Чуть подробнее расписал здесь:
https://github.com/mtxadmin/ublock/blob/master/docs/hosts_file_performance_ru.md
Но я вполне могу быть неправ, конечно.

**Comment by dimqua** [comment]
Не могу ни подтвердить, ни опровергнуть, т.к. я использую фильтрацию на уровне DNS. Может быть имеет смысл и такой список доменов сделать? Многие используют pi-hole и подобные решения, да и на мобильных устройствах без root весьма популярны DNS66 и Blokada.

**Comment by mtxadmin** [comment]
Не знаю, есть ли смысл? Формат hosts очень популярен и универсален, а другие форматы довольно нишевые, на мой взгляд.

**Comment by mtxadmin** [comment]
Кстати, Blokada вполне себе загружает файл hosts - это отмечается даже на filterlists.com

**Comment by mtxadmin** [comment]
Для Blokada v4 (v5 пока не поддерживает астериски) есть экспериментальный файл hosts_blokada.txt

Он хотя и экспериментальный, но крутится на тестовых устройствах нормально и в одиночку. Ну и очень компактный при этом.
