### ISSUE TITLE
Invalid domains - IDN should be converted to ACE

### ISSUE THREAD

**Issue by aravindvnair99** [mtxadmin/ublock#32]
Regression of #25 

```
Sample of invalid domains:
      - minecräft.com
      - rëddït.com
      - yoütu.be
      - yoütübe.co
      - yoütübe.com
```

**Comment by mtxadmin** [comment]
Oh, I fixed them in source file [_malware_typo](https://github.com/mtxadmin/ublock/blob/master/hosts/_malware_typo), but didn't update in hosts file. Oops :-) Fixing.
