### ISSUE TITLE
embed.typeform.com

### ISSUE THREAD

**Issue by aravindvnair99** [mtxadmin/ublock#36]
Blocking this breaks websites. Typeform is a "form as a service".

Example: https://www.mergeintern.com/hackyou

Reference:

- https://www.typeform.com/
- https://en.wikipedia.org/wiki/Typeform_(service)

**Comment by mtxadmin** [comment]
Sorry, accidently closed :-)

**Comment by aravindvnair99** [comment]
> Sorry, I accidently closed :-)

@mtxadmin As the issue has been fixed, I believe it can be closed.
