### ISSUE TITLE
Не загружается в Firefox

### ISSUE THREAD

**Issue by sergeykorablin** [mtxadmin/ublock#39]
Странная ситуация, список не работает в Firefox, но работает в Edge на том же ПК.
При добавлении списка в Firefox не опряделяется его имя и не загружается содержимое. В чем может быть причина?

![image](https://user-images.githubusercontent.com/37698016/117536927-8b66e200-b006-11eb-96c1-9abcb135ccea.png)

Firefox 88.0.1
uBlock Origin v1.35.2

**Comment by mtxadmin** [comment]
Да, действительно странная ситуация. Путь правильный, должно работать.

Можно заглянуть в лог загрузок, например - что там пишет?

**Comment by mtxadmin** [comment]
Я имел в виду лог uBlock Origin. Вызывается там из меню
![](https://user-images.githubusercontent.com/45539811/111190967-aac62d80-85c8-11eb-9e69-6c7bead20073.png)

**Comment by sergeykorablin** [comment]
При добавлении списка вот такая ошибка в логе
![image](https://user-images.githubusercontent.com/37698016/117568075-6b4b2780-b0c7-11eb-81f6-acce8e1aee80.png)

**Comment by mtxadmin** [comment]
Упс, да, моя ошибка.

Исправил, должно работать

**Comment by mtxadmin** [comment]
Интересно, а у меня тоже в Firefox перестало грузиться, хотя ошибок нет. Надо смотреть глубже.

**Comment by sergeykorablin** [comment]
теперь
![image](https://user-images.githubusercontent.com/37698016/117572680-a4da5d80-b0dc-11eb-903d-29e4f6bcc995.png)

**Comment by mtxadmin** [comment]
Да, это были именно они (хотя я думал, проблема во множественных вложениях, а оказалось, что в путях)

Теперь грузится и в Firefox. Спасибо за помощь.

**Comment by mtxadmin** [comment]
0 из 0 - это что-то на вашей стороне. Если с интернетом, прокси, и т.п. всё нормально, давайте логи uBlock Origin в момент загрузки.

Проверку работоспособности можно брать любую по вкусу. Я еще не видел ни одной, которая бы не говорила, что все блокируется на ура и полностью.

**Comment by mtxadmin** [comment]
Кажется, я понял, в чём у вас может быть проблема. В данной подписке активно используется разделение доменов и правил в отдельные файлы, которые подключаются из корневого файла директивой !#include . Она есть в uBlock Origin, но её нет во многих старых адблокерах, том же AdBlock Plus, до сих пор используемом.

Если так, то переходите на светлую сторону. У uBlock Origin там еще под капотом много всего хорошего и нового.

**Comment by mekuto** [comment]
Похоже я тоже догадался, использую uBlock Origin, версия 1.14.22, которая идет репозиториях дистрибутива, наверное очень древняя версия и некоторого функционала нет. Текущая версия uBlock Origin 1.41.6. На данный момент у меня дополнение не обновлено.
Спасибо.

**Comment by mtxadmin** [comment]
Да, нужно обновлять не только списки хостов и правил, но и сам движок баннерорезки - там время от времени появляется что-то новое. Благо, что и то и другое обновляется само и автоматически :-)
