### ISSUE TITLE
Impossible to switch to Theater Mode/Default view with Classic YouTube layout.

### ISSUE THREAD

**Issue by Marek33** [mtxadmin/ublock#4]
With the filter called **_Yet another small block filter list_** _YouTube_ does not allow me, to switch Theater Mode/Default view with Classic YouTube layout. I'm using YouTube Switch for Chromium and YouTube Classic for Firefox/Waterfox, since the older layout, is way better.

**Comment by mtxadmin** [comment]
Hmm.. I have tried just now - YouTube was switch to Theater Mode view (and back) as usual.

Maybe it is a conflict with those extentions? Will try them later.

**Comment by Marek33** [comment]
Did you try the older design as well? With new design it works without problem, but not with the old design, which is much better.

It could be, but there is almost no other way to use the older design, which is so much better than the newer one.

**Comment by mtxadmin** [comment]
Steps to reproduce by now:

1. I disabled the filter list "Yet another small block filter list" (but not the default ones)
2. I was able to reach the older Youtube design by adding /videos?disable_polymer=1 to channel URL.
3. When playing videos, I cannot see the Theater mode button in the player. But it is not this filterlist issue - it is still disabled, and the uBlock logger panel doesn't show blocks by the filterlist. There are only EasyList and others, and those blocks seem good for me (doubleclick.net and other marketing stuff), but I didn't investigate deeper.

When I enabled "Yet another small block filter list" again I see some additional blocks - it is ok, just as intended.

**Comment by Marek33** [comment]
No, you need to have the **_Yet another small block filter list_** enabled, with the old design, since that causes this issue. _The only fix for now, is to whitelist, the YouTube domain, in the uBlock Origin, which brings back the ads on the video, so it's not a proper solution._ With the Classic YouTube for Firefox (easiest way), and having any YouTube video open, you can see, that it just won't work. After that, you will see, that no matter how many times, you click, you can't switch to the Theater/Default modes.

**Comment by mtxadmin** [comment]
I still cannot reproduce the problem. Extended steps:

1. Download and Install the Chrome from the scratch
2. Install uBlock Origin extension
3. Update default filterlists
5. Open some Youtube video and see the Theater mode button is working

For now, all seems ok

6. Search and install "Classic Youtube" extention. Took first:  https://chrome.google.com/webstore/detail/youtube-classic-restore-y/aooobjmnokciopfgejdlbnklafighoaj
7. Open some Youtube video and see the Theater mode button is working

Add filterlist

8 . In uBlock Origin add custom filterlist: 
https://raw.githubusercontent.com/mtxadmin/ublock/master/it
9. See that its rules are loaded
10. Open some Youtube video and see the Theater mode button is still working.

Please, install another browser from scratch too for testing.

**Comment by Marek33** [comment]
Yes, I did almost everything as you said (except using that extension, since I don't trust it), but the result is completely the same.

Also, what kind of list is that? I'm using this one for the FilterList site: https://raw.githubusercontent.com/mtxadmin/ublock/master/it

**Comment by mtxadmin** [comment]
> I'm using this one for the FilterList site

Are you kidding? They are the same :-)

> but the result is completely the same.

Sorry, but I tried to reproduce your issue twice with no results.

**Comment by Marek33** [comment]
Sorry, I did not realize it, since when I opened your link, since it was way too short, and the one, which I have is very long. Hmm, when I add it, I have _22, 013 used out of 29,451_. 

Do you have a Discord, so I could easily send you the file, with those, which I have?

**Comment by Marek33** [comment]
I still have the issue of not being able to switch the theater mode, like I wrote before, so I would like to know if you could look further into that, since it's definitely caused by that filter, which I mentioned. However, I don't get, why there are categories, instead of all links, like in other filters. Currently, I have 25,888 used out of 34,447.

Also, I tried it, with the YouTube Classic extension as well, even if it seems that YouTube will remove the old design in the future.

**Comment by mtxadmin** [comment]
I suppose, YouTube comments may be hidden when cookies are disabled. At least, it behaves that way in one of my test browsers.

**Comment by Marek33** [comment]
Can you change it, so we can see the comments?

Also, what about the switching?

**Comment by mtxadmin** [comment]
See your browser settings. Maybe I am wrong about cookies, of course.

**Comment by Marek33** [comment]
Unfortunately, it doesn't work, with cookies disabled or enabled. When I have them disabled, and I don't use your filter, it works, so there is something in the list, which blocks it, along with switching to the theater design.

**Comment by mtxadmin** [comment]
Sorry, I can't reproduce it.

**Comment by Marek33** [comment]
Are you using the YouTube Classic Extension, and do you have the **Yet another small block filter list** with uBlock Origin? Do you have the **34,505** lines on there? And lastly, are you using the latest Firefox? Or some of these three browsers _Waterfox, Ungoogled or Iridium_? The Iridium and Ungoogled are using older versions of Chrome, but that doesn't matter, for it, since it doesn't work on Brave as well, which is using the latest Chrome version as far as I know.

Also, do you have a Discord?

**Comment by Marek33** [comment]
@mtxadmin  Well, have you checked the Firefox, Waterfox Classic, Ungoogled and Iridium with the YouTube Classic? I would like to close this issue, but I can't since the problem is still there.

It also disables any background like on the Moddb or any logos (Google and YouTube), and on Gmail, even sign in.

**Comment by mtxadmin** [comment]
Thanks for information.

Logos, backgrounds and telemetry/statistics are blocked intentionally. 
/watch.js is yandex.metrica script which can be found on many resources too. But not on Youtube, of course - it belongs to Google, their competitor. Good, I made an exception for youtube.com - please, update the filter and see possible changes.

**Comment by Marek33** [comment]
Thanks! Now it seems to be working on the Chromium. Tomorow, I will try other browsers, but it should work on all of them.

There are still these things blocked:
_||youtube.com/api/stats/$important
/youtubei/v1/log_event
||youtube.com/error__

And the YouTube and Google logos are blocked: 
**/logo_$important,image** and **##.logo** are blocked.
