### ISSUE TITLE
neocities.org and its websites break

### ISSUE THREAD

**Issue by asakura42** [mtxadmin/ublock#40]
For example, try open https://spyware.neocities.org

**Comment by mtxadmin** [comment]
neocities.org was in CoinBlockerList. It seems, later it was narrowed to p2pool.neocities.org (or maybe it was my mistake). Of course, you are right, it is obvious false positive. Thanks.

**Comment by asakura42** [comment]
Yep, but even with unblocked neocities.org some sites have broken css, look:

![pic-selected-210517-2227-29](https://user-images.githubusercontent.com/51290160/118545557-464d5900-b746-11eb-8987-ef6ca41ab50b.png)

Sometimes all that blocking things are very useful (thank you for it) but I want to disable it for some websites. Do you know how can I make it?

**Comment by mtxadmin** [comment]
Yes, general rule, removing backgrounds, sometimes misses. I made rules for that site. It is enough?

The site author wanted black page and white text, now it is vice versa :-) More readable, I think.

**Comment by asakura42** [comment]
Thanks!

**Comment by mtxadmin** [comment]
And one more correction for the footer text. Please update.
