### ISSUE TITLE
links.duckduckgo.com

### ISSUE THREAD

**Issue by PSalant726** [mtxadmin/ublock#41]
https://github.com/mtxadmin/ublock/commit/73bc6a318a2970cc85e57df3e4d6b5e378498c1a introduced blocking of `links.duckduckgo.com`, which is required to load DuckDuckGo search results. This should be removed.

**Comment by mtxadmin** [comment]
Hmm.. I often use Duckduckgo on several browsers and it works ok while links.duckduckgo.com is blocked.

**Comment by PSalant726** [comment]
You are correct - upon further testing, this was my mistake.
