### ISSUE TITLE
vk.com и championat.com

### ISSUE THREAD

**Issue by AllPlas** [mtxadmin/ublock#42]
vk - Сломались сообщения.
championat.com - Не юзабилен.

**Comment by mtxadmin** [comment]
Сломался один из тестовых браузеров - Opera VPN. Пока занимаюсь восстановлением.

**Comment by mtxadmin** [comment]
С championat.com интересная история. Ну, то, что он нашпигован рекламой фонбета и рамблера, это полбеды. Но он еще и внезапно ломает себе верстку через полминуты внутренним скриптом, почему-то. Пришлось поправить, но ушла и возможность залогиниться там.

**Comment by mtxadmin** [comment]
С сообщениями в веб-версии VK, действительно, проблема.

**Comment by mtxadmin** [comment]
А попробуйте сейчас, пожалуйста
