### ISSUE TITLE
Истории ВКонтакте

### ISSUE THREAD

**Issue by matveytrik** [mtxadmin/ublock#43]
Здравствуйте! Понравилось пользоваться вашими фильтрами, но не работают истории ВКонтакте. Скажите, можно ли их как-нибудь включить?

**Comment by mtxadmin** [comment]
Честно говоря, пока не знаю, что там за истории, посмотрю завтра-послезавтра на тестовой машине.

**Comment by mtxadmin** [comment]
А попробуйте сейчас обновить список и посмотреть, пожалуйста
