### ISSUE TITLE
Падает авито

### ISSUE THREAD

**Issue by egslava** [mtxadmin/ublock#44]
https://avito.ru — не работает поисковая строка, по сути, сайт неработоспособный становится.

**Comment by mtxadmin** [comment]
Спасибо за pull request! Не ожидал, что блокировка sentry может приводить к таким странностям.

**Comment by egslava** [comment]
А что такое sentry вообще, если не секрет?

**Comment by mtxadmin** [comment]
Возможно, что на разных серверах оно работает по разному, так что стопроцентно точно неизвестно. Меня как-то напрягло sentry.io (например) - ну нафиг эту телеметрию. И, главное, и без этого всё работает. Но, видимо, не всегда.
