### ISSUE TITLE
False positive bitcanna.io

### ISSUE THREAD

**Issue by BitCannaGlobal** [mtxadmin/ublock#48]
BitCanna is now marked in your list. BitCanna is not a company involved in spam, but focusses on solving issues in the cannabis industries using blockchain technology. Please remove our domain from your list (https://raw.githubusercontent.com/mtxadmin/ublock/master/hosts.txt). Thanks!

**Comment by mtxadmin** [comment]
It seems, your domain was involved in some browser-mining activity about a year ago. I see, almost all my colleagues were removed the domain from their lists. Ok, I removed it too.

**Comment by BitCannaGlobal** [comment]
Good day

Thanks!

With kind regards
The BitCanna team
