### ISSUE TITLE
zkillboard.com

### ISSUE THREAD

**Issue by r0vast** [mtxadmin/ublock#49]
Киллборту то за что? Сайт тесно связан с игрой EVE Online.

0.0.0.0    zkillboard.com
0.0.0.0    image.zkillboard.com
0.0.0.0    sn-fr.zkillboard.com
0.0.0.0    www.zkillboard.com

**Comment by mtxadmin** [comment]
Упс, она случайно затесалась в файлик со всякими казино. Убрал.
