### ISSUE TITLE
Piped (YouTube privacy-friendly frontend) doesn't work

### ISSUE THREAD

**Issue by Piber0** [mtxadmin/ublock#51]
https://github.com/mtxadmin/ublock/blob/242fb4b294a61e756afdfabee10c39508d960d6f/filters/_removeparams#L743

This line prevents Piped from working. So I propose `$removeparam=source,domain=~youtube.com|~kavin.rocks`. Ideally, we should also add the address of the [community instances](https://github.com/TeamPiped/Piped/wiki/Instances).

**Comment by mtxadmin** [comment]
Yes! Thank you for pointing out the issue.

**Comment by mtxadmin** [comment]
As you can see, earlier I saw this bug on Youtube, it seems, now it's time for youtube-related projects :-)

Made a list of exclusions

**Comment by mtxadmin** [comment]
It works! :-)

For instance: https://piped.kavin.rocks/watch?v=BYVZh5kqaFg
