### ISSUE TITLE
Twitter partially broken

### ISSUE THREAD

**Issue by Piber0** [mtxadmin/ublock#52]
https://github.com/mtxadmin/ublock/blob/242fb4b294a61e756afdfabee10c39508d960d6f/filters/_removeparams#L621

This line partially breaks Twitter. I propose : 
`$removeparam=/referrer/,domain=~twitter.com|~twitter3e4tixl4xyajtrzo62zg5vztmjuricljdp2c5kshju4avyoid.onion`

**Comment by mtxadmin** [comment]
Hmm... It runs smoothly as for me. Can you show screenshots or logs?

**Comment by mtxadmin** [comment]
Yes, you were right... Now I see this error - in inner requests to https://twitter.com/i/api/graphql/
