### ISSUE TITLE
Nextdns dashborad broken

### ISSUE THREAD

**Issue by Piber0** [mtxadmin/ublock#53]
https://github.com/mtxadmin/ublock/blob/78b3ffa3533c31cd8c02099c0448b84e42045b46/filters/_removeparams#L262

This line prevents Nextdns dashbord from working.
![Sans titre](https://user-images.githubusercontent.com/95138823/208783963-8f43e486-83a5-4b9d-96c7-e86fae8cf9f9.png)

More precisely the request `https://api.nextdns.io/profiles/`

**Comment by mtxadmin** [comment]
Made an exclusion, please check

**Comment by Piber0** [comment]
I've checked, everything works perfectly
