### ISSUE TITLE
Which is better for a system that supports the wildcard format?

### ISSUE THREAD

**Issue by GiddyGoatGaming** [mtxadmin/ublock#54]
I was wondering if the Blokada version is just as good as the host.txt version but with a smaller file size, fewer entries and wildcard support or if the full version covers more grounds

**Comment by mtxadmin** [comment]
I am interested in this topic too. For Android, I found only Blokada app (and described about it [here](https://github.com/mtxadmin/ublock/blob/master/docs/hosts_file_blokada_en.md)). One can use NextDNS for any system, but the free version is unusable - query limit is far too low. There are several different tools, but they don't support wildcards.

**Comment by mtxadmin** [comment]
Or did I understand the question wrong? Blokada hosts and full hosts are making from the same set of sources, and they differentiate only with format (and compiling date - Blokada is usually slightly newer)

**Comment by GiddyGoatGaming** [comment]
> Or did I understand the question wrong? Blokada hosts and full hosts are making from the same set of sources, and they differentiate only with format (and compiling date - Blokada is usually slightly newer)

that answered my question perfectly. Thanks

**Comment by ignoramous** [comment]
*rdns dev here*

[Nebulo](https://github.com/ch4t4r/nebulo) supports wildcards from what I recall. In my experience, it had been more stable than Blokada, so that's what I used, and still recommend.

**Comment by mtxadmin** [comment]
@ignoramous, thanks for the tip. I updated [docs](https://github.com/mtxadmin/ublock/blob/master/docs/hosts_file_blokada_en.md), that's interesting.
