### ISSUE TITLE
4pda.ru/forum

### ISSUE THREAD

**Issue by Lichtenshtein** [mtxadmin/ublock#6]
Полностью ломает поиск и множество кнопок цитирования/ответов на форуме 4pda.

**Comment by mtxadmin** [comment]
Да, похоже на то, спасибо. Сейчас подумаю, что с этим сделать.

**Comment by mtxadmin** [comment]
Поиск поправил, с кнопками посмотрю позже.

**Comment by mtxadmin** [comment]
Повторяющиеся кнопки под каждым постом всё-таки мне кажутся плохим интерфейсным решением и визуальным мусором. Но если они вам нужны, добавьте правило в свои фильтры: 
4pda.ru#@#td.formbuttonrow

**Comment by Lichtenshtein** [comment]
Добавил, спасибо. С 4pda теперь всё ок.
