### ISSUE TITLE
win10tweaker.ru

### ISSUE THREAD

**Issue by matveytrik** [mtxadmin/ublock#63]
Скажите, пожалуйста, а почему этот сайт заблокирован? Вижу в списке ссылку на статью сайта Habr, но она уже недоступна. Ведь в этой программе нет вирусов и сам разработчик отвечал на эти обвинения. Сам частый посетитель форума Win10Tweaker и неудобно что он блокируется. Ссылки на его ответ прикрепляю:

https://www.youtube.com/watch?v=gLkIO4JMEFc
https://win10tweaker.ru/forum/topic/%d0%ba%d0%bb%d0%b5%d0%b2%d0%b5%d1%82%d0%b0-%d0%b2-%d0%b2%d0%b8%d0%b4%d0%b5%d0%be-%d0%bf%d1%80%d0%be-win10tweaker/#postid-29722

**Comment by mtxadmin** [comment]
Да, оригинальный разбор недоступен https://habr.com/ru/post/557388/, 
но есть копии:
https://pikabu.ru/story/byekdor_v_win_10_tweaker_ili_sovremennyie_metodyi_borbyi_s_piratstvom_8227558
https://itnan.ru/post.php?c=1&p=557388

Я бы поостерегся использовать такое.
