### ISSUE TITLE
tomato-timer.com is broken

### ISSUE THREAD

**Issue by adworacz** [mtxadmin/ublock#7]
Offending rule:
```
##[id^="timer"]:not(html):not(body):not(article)
```

Basically, the Pomodoro timer website is supposed to have a count down timer, and it's completely hidden by this list with no way to unbreak it (that I could find).

**Comment by mtxadmin** [comment]
Thanks for reporting!

That rule intended to hide all "discount" ad counters no matter where. But, of course, Pomodoro is should not be blocked, it is a good thing :-) 

Unblocked.

**Comment by mtxadmin** [comment]
By the way, browser notifications of that timer are useful? (I am asking because many websites use them for spam)

**Comment by adworacz** [comment]
Meh, I think it's a toss up. The website already emits a beeping noise when the timer is finished, so the extra "times up!" notification is just that - extra.

I'm okay without it personally, but someone else might prefer to see it.
