### ISSUE TITLE
Reddit blocked pop up list

### ISSUE THREAD

**Issue by MrMarvel** [mtxadmin/ublock#76]
I can not post with this filter list because it blocks Flair list
![image](https://github.com/mtxadmin/ublock/assets/24212110/4ed318bb-0e79-47e8-90b6-32794811bc5a)

**Comment by mtxadmin** [comment]
Thanks for report!

I found and [disabled](https://github.com/mtxadmin/ublock/commit/99990f3a9e8bf5e599aad75fc2c3419c25ed1026) corresponing rule. Initially it was meant to hide an empty block after the post.
