### ISSUE TITLE
Drom (hosts.txt -> Pi-Hole)

### ISSUE THREAD

**Issue by r0vast** [mtxadmin/ublock#79]
api.drom.ru
Фильт загружен в Pi-Hole. В мобильном приложении "Дром Авто" на iOS 16 не прогружаются обьявления хотя в броузере работает и на андройд устройстве в приложении тоже работает.

**Comment by mtxadmin** [comment]
Сделайте пока временное исключение, пожалуйста, хостовые фильтры обновляются небыстро
