### ISSUE TITLE
Surveymonkey.com is broken

### ISSUE THREAD

**Issue by L33Tech** [mtxadmin/ublock#8]
Select an option question selection boxes are unclickable.

**Comment by mtxadmin** [comment]
Sorry, but I don't like those widgets from similar poll/quiz sites.

**Comment by L33Tech** [comment]
It breaks functionality when filling out a form for work though on the main site, it's not a widget?

**Comment by mtxadmin** [comment]
Ok, maybe you are right :-)

Try now, please.

**Comment by L33Tech** [comment]
Issue still persists, I'm using the hosts.txt version

**Comment by mtxadmin** [comment]
Script fot generating hosts.txt is being refactored now. New version will be ready tomorrow.

**Comment by mtxadmin** [comment]
Hosts.txt does not contain surveymonkey hosts now.

**Comment by L33Tech** [comment]
Fixed, thanks!
