### ISSUE TITLE
Точки на карте перестают масштабироваться при включенном фильтре

### ISSUE THREAD

**Issue by NoAdO** [mtxadmin/ublock#82]
Здравствуйте!

Понимаю, что звучит, как бред, но если я использую https://raw.githubusercontent.com/mtxadmin/ublock/master/filters/yandex и открываю https://yandex.ru/maps/geo/stantsiya_matveyevskaya/5262747426/?ll=37.743935%2C55.662457&z=10 (ссылка для примера, любая работа с картами такая) и изменяю масштаб, точки POI, например "избранного" или найденный результат, остаются на экране в тех же местах что были, а карта - масштабируется. Отключаю список, обновляю страницу через F5, всё масштабируется корректно. Включаю обратно - снова нет.
![2024-03-28 170518](https://github.com/mtxadmin/ublock/assets/22981424/e6ed5a78-59a6-466c-8a2f-ab54dcbaa031)
![2024-03-28 170540](https://github.com/mtxadmin/ublock/assets/22981424/05c40f03-b3f0-4c45-ba94-79630022d28c)

**Comment by mtxadmin** [comment]
Спасибо за исследование.

Когда-то увидел эту строку с заданием константы в Ru AdList и скопировал с мыслью разобраться, как и зачем это. Руки не дошли, увы. Сейчас посмотрел, там коллеги уже убрали. Тоже закомментировал в этом блоклисте.

**Comment by NoAdO** [comment]
Отлично, спасибо. Если что-то ещё найду, отпишусь по такой же схеме.
